### ISSUE TITLE
3.5.2-SNAPSHOT android-maven-plugin

### ISSUE THREAD

**Issue by imminent** [stephanenicolas/Quality-Tools-for-Android#1]
I don't see (and maven isn't resolving) 3.5.2-SNAPSHOT at https://oss.sonatype.org/content/repositories/jayway-snapshots/com/jayway/maven/plugins/android/generation2/android-maven-plugin/ is it in a different place? It seems that 3.5.2 is necessary for the UIAutomator. 

> [ERROR]   The project com.octo.android:android-sample:0.0.1-SNAPSHOT (/Users/dandre/Android_Development/Quality-Tools-for-Android/android-sample/pom.xml) has 2 errors
> [ERROR]     Unresolveable build extension: Plugin com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.2-SNAPSHOT or one of its dependencies could not be resolved: Failure to find com.jayway.maven.plugins.android.generation2:android-maven-plugin:jar:3.5.2-SNAPSHOT in http://oss.sonatype.org/content/repositories/jayway-snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of oss.sonatype.org-jayway-snapshots has elapsed or updates are forced -> [Help 2]
> [ERROR]     Unknown packaging: apk @ line 13, column 13
> [ERROR]  
> [ERROR]   The project com.octo.android:android-sample-ui-tests:0.0.1-SNAPSHOT (/Users/dandre/Android_Development/Quality-Tools-for-Android/android-sample-ui-tests/pom.xml) has 1 error
> [ERROR]     Unresolveable build extension: Plugin com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.2-SNAPSHOT or one of its dependencies could not be resolved: Failure to find com.jayway.maven.plugins.android.generation2:android-maven-plugin:jar:3.5.2-SNAPSHOT in http://oss.sonatype.org/content/repositories/jayway-snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of oss.sonatype.org-jayway-snapshots has elapsed or updates are forced -> [Help 2]

**Comment by stephanenicolas** [comment]
Sorry, the announcement of this contribution was a bit too premature. I commited this pull request to android maven plugin a few days ago and Manfred (the author the android maven plugin) is integrating it. You can follow up the status of this pull request [here](https://github.com/jayway/maven-android-plugin/pull/185).
