### ISSUE TITLE
Code Coverage Missing for Instrumentation Tests

### ISSUE THREAD

**Issue by rossimo** [stephanenicolas/Quality-Tools-for-Android#11]
I've tested using the EMMA, Cobertura, and Jacoco profiles, but I can't seem to get any code coverage results from the instrumentation tests. I deleted 'MyActivityTest.java' to keep the Robolectric tests from running to ensure only instrumentation tests are avaliable.

Should I be getting code coverage results from instrumentation tests? I'm running ADB with root access.

**Comment by stephanenicolas** [comment]
Hi rossimo,

sorry for the delay, I was in holidays. 

You will get code coverage in both layouts. It works now but worked as well before. If you follow the instructions given in the wiki, can you get code coverage ?

Where is the problem, when you import in sonar (if you use it), or do you wanna get code coverage in standalone ?
Is your device rooted for emma ?

**Comment by stephanenicolas** [comment]
This question is closed as I believe everything is solved in actual repo. Please reopen if problem persists.
