### ISSUE TITLE
Jacoco profil not working

### ISSUE THREAD

**Issue by Deyine** [stephanenicolas/Quality-Tools-for-Android#18]
Hi Stephane
thanks for sharing this config, it was very useful for me. 

However, jacoco profil not work for me, as sonar show only "Unit tests coverage" block with 0%.

![image](https://f.cloud.github.com/assets/193329/1415508/140f1130-3f09-11e3-8505-6373f6cfe15e.png)

Emma profil works fine

![image](https://f.cloud.github.com/assets/193329/1415503/c2dd0efc-3f08-11e3-836d-ef14bc3c2ece.png)

Sonar 3.7.3 .

Do you have any idea about this issue ?

**Comment by stephanenicolas** [comment]
Could you solve this ? I also faced some troubles with newest jacoco
release, but had no time for investigating further.

Sorry for the delay to answer.

S.

**Comment by Deyine** [comment]
Yes, it was my fault. "Integration Tests" widget was disabled by default in Sonar Dashboard config (shame on me :) ).
however, unit tests coverage still 0%
