### ISSUE TITLE
Missing extension android-maven-plugin:3.5.2

### ISSUE THREAD

**Issue by Hirschen** [stephanenicolas/Quality-Tools-for-Android#2]
When doing mvn clean install:

Unresolveable build extension: Plugin com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.2-SNAPSHOT or one of its dependencies could not be resolved: Failure to find com.jayway.maven.plugins.android.generation2:android-maven-plugin:jar:3.5.2-SNAPSHOT in http://oss.sonatype.org/content/repositories/jayway-snapshots/

Seems like the snapshot is missing at the specific address. Anything Im doing wrong maybe?

**Comment by stephanenicolas** [comment]
This issue is a duplicate of issue #1.
