### ISSUE TITLE
Update to version 3.5.2 of the android-maven-plugin

### ISSUE THREAD

**Issue by biafra23** [stephanenicolas/Quality-Tools-for-Android#6]
Version 3.5.2 of the android-maven-plugin has been released and does not need a special SNAPSHOT repo to be configured.

**Comment by stephanenicolas** [comment]
Hi biafra23,

thanks for this follow-up. 

Actually, I participate quite a lot to MAP development this time, especially to get more things integrated with QAT. 
Version 3.5.2 has been released, but I am still waiting for another pull request to be integrated (to get monkey runner with MAP), so the version of MAP has been ported to 3.5.3-SNAPSHOT.

Things should stabilize within a few weeks as the last thing I want to add to MAP would be monkey runner (not monkey) support and that should be done quickly now. Meanwhile, we have to leave with this SNAPSHOT versions.

Stéphane
